### ISSUE TITLE
Compatibility with Flux and GitOps Toolkit

### ISSUE THREAD

**Issue by stefanprodan** [openservicemesh/osm#1424]
Currently is not possible to manage OSM install/upgrades using a [GitOps approach](https://toolkit.fluxcd.io/). 

Giving that OSM uses Helm, the chart could be published to a Helm Repository hosted on GitHub Pages. In FluxCD org we use a [dedicated repo](https://github.com/fluxcd/charts) to host the charts and we use GH Actions to package and publish the chart as part of the release process.

Assuming OSM would host the charts on GitHub, one could automate the OSM deployment with Flux:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1alpha1
kind: HelmRepository
metadata:
  name: osm
  namespace: gitops-system
spec:
  interval: 1m
  url: https://openservicemesh.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: osm
  namespace: osm-system
spec:
  interval: 1h
  chart:
    name: osm
    version: "^0.1.0" # <- automated upgrades
    sourceRef:
      kind: HelmRepository
      name: osm
      namespace: gitops-system
  values:
    OpenServiceMesh:
      image:
        registry: openservicemesh
        pullPolicy: IfNotPresent # <- this should be in values.yaml
        tag: v0.1.0 # <- this should be in values.yaml
      imagePullSecrets: {} # <- this should be in values.yaml
```

Note that the default image values used by OSM are not suitable for production use. The tag is set to `latest`, there is a pull secret set to ACR?, the pull policy is set to `always`. All these settings can't work in a GitOps driven pipeline where the image tag must be immutable. Another issue is that Helm v3 doesn't upgrade CRDs, changing the SMI version would result in a broken upgrade since Helm ignores the crds dir after install. According to [Helm docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts) OSM should provide a dedicated chart for CRDs.

**Scope (please mark with X where applicable)**
- [ ] New Functionality
- [x] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [ ] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

**Possible use cases**

Allow OSM installation and upgrades to be managed from Git e.g. Flux, Azure Arc.
