### ISSUE TITLE
Integrate OSM with OPA envoy plugin

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1874]
**Please describe the Improvement and/or Feature Request**
Integrate OSM with the ability to execute policies with OPA via the OPA envoy plugin https://github.com/open-policy-agent/opa-envoy-plugin

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [X]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
As a user, I want to use the OPA policies to do authorization for my applications.

**Comment by Pindar** [comment]
This seems connected to the following general issue https://github.com/servicemeshinterface/smi-spec/issues/213

**Comment by draychev** [comment]
> This seems connected to the following general issue [servicemeshinterface/smi-spec#213](https://github.com/servicemeshinterface/smi-spec/issues/213)

Indeed!  We will prototype OPA + OSM integration and will keep you posted, @Pindar

**Comment by eduser25** [comment]
On the way: https://github.com/openservicemesh/osm/pull/3312

**Comment by draychev** [comment]
@Pindar @infbase 
We have an OSM release with initial support for Envoy OPA -- https://github.com/openservicemesh/osm/releases/tag/v0.8.4-rc.1
Would you be so kind to download this release and try the OPA integration.

The output of `osm version` for the new release: 
```bash
./osm version
Version: v0.8.4-rc.1; Commit: 3ecafb94cb43a3828e905cea853e238ccc5a7ee1; Date: 2021-05-10-16:59
```

Initial document on how to enable the integration is here:  https://github.com/openservicemesh/osm/blob/release-v0.8/docs/content/docs/external_auth_opa.md

Once you install osm (with `./osm install`) you need to update the ConfigMap.
I did it using this:
```bash
#!/bin/bash

kubectl patch ConfigMap osm-config -n osm-system --type merge --patch '{"data":{"inbound_extauthz_enable": "true"}}'
kubectl patch ConfigMap osm-config -n osm-system --type merge --patch '{"data":{"inbound_extauthz_address": "opa.opa.svc.cluster.local"}}'
kubectl patch ConfigMap osm-config -n osm-system --type merge --patch '{"data":{"inbound_extauthz_port": "9191"}}'
kubectl patch ConfigMap osm-config -n osm-system --type merge --patch '{"data":{"inbound_extauthz_statprefix": "authz_opa"}}'
kubectl patch ConfigMap osm-config -n osm-system --type merge --patch '{"data":{"inbound_extauthz_timeout": "1s"}}'
kubectl patch ConfigMap osm-config -n osm-system --type merge --patch '{"data":{"inbound_extauthz_failuremodeallow": "false"}}'

kubectl get ConfigMap -n osm-system  osm-config -o json | jq '.data'
```

The OSM ConfigMap will look something like this:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-config
  namespace: osm-system
  labels:
    app.kubernetes.io/instance: osm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openservicemesh.io
    app.kubernetes.io/version: v0.8.4-rc.1

data:
  egress: "false"
  enable_debug_server: "false"
  enable_privileged_init_container: "false"
  envoy_log_level: error
  inbound_extauthz_address: opa.opa.svc.cluster.local
  inbound_extauthz_enable: "true"
  inbound_extauthz_failuremodeallow: "false"
  inbound_extauthz_port: "9191"
  inbound_extauthz_statprefix: authz_opa
  inbound_extauthz_timeout: 1s
  permissive_traffic_policy_mode: "false"
  prometheus_scraping: "true"
  service_cert_validity_duration: 24h
  tracing_enable: "false"
  use_https_ingress: "false"
```

Look forward to your feedback!
