### ISSUE TITLE
Required resource setting for injected containers

### ISSUE THREAD

**Issue by addozhang** [openservicemesh/osm#2472]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

We have quota configured for each namespaces and injected containers have no resourte limitation setting. Bellow error occurs when pod initializing.

```
Error creating: pods "xxxxx-gray-5444bddb9-cmbgd" is forbidden: [minimum cpu usage per Pod is 10m.  No request is specified., minimum memory usage per Pod is 2Mi.  No request is specified., maximum cpu usage per Pod is 4.  No limit is specified., maximum memory usage per Pod is 6Gi.  No limit is specified., minimum cpu usage per Container is 10m.  No request is specified., minimum memory usage per Container is 2Mi.  No request is specified., maximum memory usage per Container is 6Gi.  No limit is specified., maximum cpu usage per Container is 4.  No limit is specified., minimum cpu usage per Container is 10m.  No request is specified., minimum memory usage per Container is 2Mi.  No request is specified., maximum cpu usage per Container is 4.  No limit is specified., maximum memory usage per Container is 6Gi.  No limit is specified.]
```

**Comment by eduser25** [comment]
@addozhang We do set limits on OSM, I'll revisit the ones per container on the pod.

However, see `minimum cpu usage per Pod is 10m.  No request is specified.`, that seems to come from the very pod you are trying to push. Can you share with us the full yaml of the pod trying to be pushed here?

**Comment by addozhang** [comment]
@eduser25 yes, we have `limitranges` per namespace. It also has default resource setting for container. But the default config is applied before admission webhook phase. So the injected containers have no default limit applied.

You can try with below yamls.

```yaml
apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: null
  name: limits-example
spec:
  limits:
  - max:
      cpu: "4"
      memory: 6Gi
    min:
      cpu: 10m
      memory: 2Mi
    type: Pod
  - default:
      cpu: "1"
      memory: 200Mi
    defaultRequest:
      cpu: 10m
      memory: 10Mi
    max:
      cpu: "4"
      memory: 6Gi
    min:
      cpu: 10m
      memory: 2Mi
    type: Container
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
