### ISSUE TITLE
Bug in Liveness/Readiness rewriting for HTTPS probes

### ISSUE THREAD

**Issue by m1ghtym0** [openservicemesh/osm#2515]
**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [x ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

Liveness/Readiness rewriting results in working probes.

**Steps to reproduce the bug (as precisely as possible)**

Original probe definitions:
```
livenessProbe:
  httpGet:
    path: /status
    scheme: HTTPS
    port: 25555
  initialDelaySeconds: 10
readinessProbe:
  failureThreshold: 7
  httpGet:
    path: /status
    scheme: HTTPS
    port: 25555
```

Rewritten probe definitions:

```
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /osm-liveness-probe
    port: 15901
    scheme: HTTPS
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 7
  httpGet:
    path: /osm-readiness-probe
    port: 15902
    scheme: HTTPS
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
```

Result:
```
Readiness probe failed: Get "https://172.18.0.4:15902/osm-readiness-probe": http: server gave HTTP response to HTTPS client
Liveness probe failed: Get "https://172.18.0.4:15901/osm-liveness-probe": http: server gave HTTP response to HTTPS client
```

**How was OSM installed?**: `bin/osm install --enable-permissive-traffic-policy`

**Anything else we need to know?**:

My guess is that the probe listener is only configured for HTTP, but my envoy knowledge is not that deep.
https://github.com/openservicemesh/osm/blob/ef3366531807908a77b3dadd9c3acb921c680b6f/pkg/injector/envoy_config_health_probes.go#L83

**Environment**:
- OSM version (use `osm version`): `Version: dev; Commit: c8636620211127d23a6208ee79687e5dffec296d; Date: 2021-02-08-10:49`
- Kubernetes version (use `kubectl version`): 
  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Size of cluster (number of worker nodes in the cluster): Minikube (1)
- Others:
