### ISSUE TITLE
Allow splitting traffic to same FQDN using multiple traffic split policies matching different routes

### ISSUE THREAD

**Issue by addozhang** [openservicemesh/osm#2759]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

In 0.7.0, it works fine. But not work in 0.8.0. 

I guess it relates with logic https://github.com/openservicemesh/osm/blob/main/pkg/catalog/routes.go#L89.

```yaml
- apiVersion: split.smi-spec.io/v1alpha2
  kind: TrafficSplit
  metadata:
    labels:
      target: boot
    name: boot-gray
  spec:
    backends:
    - service: boot-prod
      weight: 100
    service: boot
- apiVersion: split.smi-spec.io/v1alpha2
  kind: TrafficSplit
  metadata:
    labels:
      target: boot
    name: boot-gray-282
  spec:
    backends:
    - service: boot-gray
      weight: 100
    service: boot
```

I think the logic of 'apex service' should be that if 'existing', append to existing `WeightedClusters` set (make `apexServices` variable as `map`, `key` is `MeshService`, and value is `OutboundTrafficPolicy`).

Current logic limits one service can have ONLY one traffice split.
