### ISSUE TITLE
OSM Validating Webhook blocks valid ConfigMap patches post upgrade

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2819]
Upgraded OSM Controlle from v0.5 to v0.8.  Used `kubectl apply` to upgrade the container, not `osm mesh upgrade`.

Tried to patch the `osm-system/osm-config` ConfigMap with:
```bash
kubectl patch ConfigMap osm-config -n osm-system -p '{"data":{"service_cert_validity_duration":"5s"}}' --type=merge
```

Observed error:
```
Error from server (
enable_privileged_init_container: must be included as it is a default field): admission webhook "osm-config-webhook.k8s.io" denied the request: 
enable_privileged_init_container: must be included as it is a default field
```

The state of the ConfigMap when this error is observed:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: osm-config
  namespace: osm-system
data:
  egress: "false"
  enable_debug_server: "false"
  envoy_log_level: error
  permissive_traffic_policy_mode: "false"
  prometheus_scraping: "true"
  service_cert_validity_duration: 24h
  tracing_address: jaeger.osm-system.svc.cluster.local
  tracing_enable: "true"
  tracing_endpoint: /api/v2/spans
  tracing_port: "9411"
  use_https_ingress: "false"
```

## Workaround:
Patched the ConfigMap with:
```bash
kubectl patch ConfigMap osm-config -n osm-system -p '{"data":{"enable_privileged_init_container":"false"}}' --type=merge
```
and then was able to apply the original patch, which failed earlier:
```bash
kubectl patch ConfigMap osm-config -n osm-system -p '{"data":{"service_cert_validity_duration":"5s"}}' --type=merge
```
