### ISSUE TITLE
Use objectSelector in ValidatingWebhookConfiguration to limit objects observed

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2926]
This GitHub Issue is for the addition of `objectSelector` to the current ValidatingWebhookConfiguration within OSM.

The VWC should only be watching the `osm-system/osm-config` ConfigMap.

Here is context on the `objectSelector`: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector

Current VWC is this:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: osm-controller
  name: osm-webhook-osm
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: ""
    service:
      name: osm-config-validator
      namespace: osm-system
      path: /validate-webhook
      port: 9093
  failurePolicy: Fail
  matchPolicy: Exact
  name: osm-config-webhook.k8s.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
    matchLabels:
      name: osm-system
  objectSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - configmaps
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
```

The goal would be to 
  1. Add an appropriate label to `osm-system/osm-config` ConfigMap (see https://github.com/openservicemesh/osm/issues/2925)
  2. change the `objectSelector: {}`
to
```yaml
  objectSelector:
    matchLabels:
      app: openservicemesh.io  # or whatever key/value we choose in #2925
```
