### ISSUE TITLE
egress: Prototype, design, and implement a gine-grained egress policy

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3045]
This issue is for the creation of a:
  - [ ] proof of concept (with a custom CRD) of an OSM, which can be configured with fine-grained egress policy
  - [ ] design proposal
  - [ ] implementation
  - [ ] integration tests

For example:
```yaml
egress:
  allow:
    - 10.0.0.1:8080
  block:
    - www.altavista.com:8080
```
