### ISSUE TITLE
Mesh catalog functions matching ServiceAccount names should also match Kind field of the policy 

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3173]
Mesh catalog functions matching ServiceAccount names should also match Kind field of the policy. So far this works because in SMI we only have one Kind (ServiceAccount).

For example:
```yaml
apiVersion: access.smi-spec.io/v1alpha2
kind: TrafficTarget
metadata:
  name: bookbuyer-access-bookstore
  namespace: bookstore
spec:
  destination:
    kind: ServiceAccount
    name: bookstore
    namespace: bookstore
  rules:
  - kind: HTTPRouteGroup
    name: bookstore-service-routes
    matches:
    - buy-a-book
    - books-bought
  sources:
  - kind: ServiceAccount
    name: bookbuyer
    namespace: bookbuyer
```

---

### References
  - **Use ServiceIdentity type in catalog APIs instead of service.K8sServiceAccount** #2218
