### ISSUE TITLE
Create osm multicluster CRD

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#3403]
**Please describe the Improvement and/or Feature Request**

The design doc :  [RFC: Multicluster osm](https://docs.google.com/document/d/1O3XcG27uryBxCHX719qYUUzAo913GoFv3LOwdnfNudQ/edit#heading=h.frj1aeltd2ge), specifies the need of a crd to support multicluster osm. 

This issue is to track the following : 
- [ ] Propose/Design a multicluster CRD (yaml only) based on the multicluster design doc 
- [ ] Create code gen helper for generation of Go Client code for the new multicluster CRD 
- [ ] Generate Go Client code for the new multicluster CRD 
- [ ] Create informers for this CRD
- [ ] creation of the CRD, deploying it via helm and setting up of the informers should be triggered only when the multicluster feature is enabled in osm #3402 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by steeling** [comment]
From https://docs.google.com/document/d/1sA03IwqC6tuJpCleGMakQpHzwFJ5ulfxzCq7iSXSqZc/edit#, we plan on augmenting the previous OSM CRD to break up the config such that there is 1 config per service per remote cluster. The new CRD will look like:

```
apiVersion: v1alpha1
kind: RemoteService
metadata:
     	name: store-clusterX
     	namespace: osm-system 
spec:
      cluster:
     	     	name: clusterX
     	     	gateway: 10.10.10.10:90         # a routable IP + port
     	     	certificate: ==               # mTLS certificates (optional)
      equivalence:     # allows multiple equivalence schemes in the future
       	serviceName: store
      	serviceNamespace: store
      	serviceAccount: store
```
