### ISSUE TITLE
MeshConfig doesn't show sidecar resources 

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#3554]
**Bug description**:

when the sidecar resources (limits and requests) are specified at the time of install, a `kubectl get meshConfig -o yaml -n osm-system ` doesn't show this field and its relevant data. 

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: We should be able to see all the resource object in MeshConfig when set. 

**Steps to reproduce the bug (as precisely as possible)**: 

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by eduser25** [comment]
Not sure what was different on Niranjan's setup but...

```
eserra@edu-linux ~/src/osm (main) $ kubectl get meshconfig osm-mesh-config -o yaml
apiVersion: config.openservicemesh.io/v1alpha1
kind: MeshConfig
...
  sidecar:
    configResyncInterval: 0s
    enablePrivilegedInitContainer: false
    envoyImage: envoyproxy/envoy-alpine:v1.18.3
    initContainerImage: eserraacr.azurecr.io/init:latest
    logLevel: debug
    maxDataPlaneConnections: 0
    resources:
      limits:
        cpu: "2"
        memory: 128M
      requests:
        cpu: "1"
        memory: 64M
....
```

that LGTM? This was running the e2e proxy resources test itself. I'll keep an eye if we see something like this again.
