### ISSUE TITLE
Local cluster endpoints for service with multiple ports are not correctly programmed

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#3777]
**Bug description**:
Local cluster endpoints for a service with multiple ports are not correctly programmed.

Consider the following k8s service :
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookstore
  name: bookstore
  namespace: bookstore
spec:
  ports:
  - name: ssh
    port: 22 # TCP based 
    protocol: TCP
  - name: web
    port: 80 # HTTP based
    protocol: TCP
  selector:
    app: bookstore
  type: ClusterIP
```

The code in https://github.com/openservicemesh/osm/blob/main/pkg/envoy/cds/cluster.go#L129-L152 incorrectly programs both the ports as endpoints for the local cluster corresponding to the `bookstore` service.

This is due to a limitation in the existing implementation where a single cluster is created for a service. This is not correct because a single local cluster cannot proxy traffic meant for different protocol ports to all the ports the same way. The problem with doing so is that in the above example, HTTP traffic will get proxied to a TCP port, and vice versa.

**Proposed fix**:
- Create cluster per service port. Cluster names should change to include the port corresponding to the cluster. If there are multiple ports on the service that are exposed, multiple local clusters must be created per pert. 
- Update the inbound HTTP routes to only reference HTTP based clusters specific to HTTP ports
- Update the inbound TCP route to only reference TCP based clusters specific to TCP ports

**Affected area (please mark with X where applicable)**:
- Control Plane        [X]
- Networking                  [X]

**Expected behavior**:
HTTP traffic should not be proxied to TCP ports, and vice versa. 

**Steps to reproduce the bug (as precisely as possible)**:
1. Create a service with multiple ports (HTTP and TCP)
2. Send HTTP traffic to the service on it's HTTP port

Since the service has a TCP port, the local cluster endpoints will incorrectly include this port.
