### ISSUE TITLE
BYO Jaeger UI dashboard not working as expected on v0.11.1-rc.1

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#4294]
**Bug description**: The Jaeger UI dashboard should show tracing for all deployments/services monitored by the mesh. However, the dashboard is not showing services deployed as part of the manual demo, even after adding the RBAC and patching the meshconfig to enable tracing and change the address. Currently only `jaeger-query` is visible in the drop down. 

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: Jaeger UI dashboard should list bookbuyer, bookstore, bookthief, and bookwarehouse services. 

**Steps to reproduce the bug (as precisely as possible)**:

1. Install osm v0.11.1-rc.1 on AKS cluster. 
2. Create a namespace called `jaeger`. 
3. Deploy a manifest to install jaeger: https://docs.microsoft.com/en-us/azure/aks/open-service-mesh-open-source-observability#deploy-jaeger-to-the-aks-cluster. 
4. Add the following RBAC for the jaeger SA: 
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: jaeger
  name: jaeger
  namespace: jaeger

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: jaeger
  name: jaeger

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger
  labels:
    app: jaeger
subjects:
  - kind: ServiceAccount
    name: jaeger
    namespace: jaeger
roleRef:
  kind: ClusterRole
  name: jaeger
  apiGroup: rbac.authorization.k8s.io
```
5. Patch the meshconfig: `kubectl patch meshconfig osm-mesh-config -n osm-system -p '{"spec":{"observability":{"tracing":{"enable":true, "address": "jaeger.jaeger.svc.cluster.local"}}}}' --type=merge` 
6. Follow the manual demo steps to create the bookbuyer, bookstore, bookthief, and bookwarehouse deployments in namespaces monitored by OSM. 
7. View the Jaeger UI via port forwarding: 
`JAEGER_POD=$(kubectl get pods -n jaeger --no-headers  --selector app=jaeger | awk 'NR==1{print $1}')`
`kubectl port-forward -n jaeger $JAEGER_POD  16686:16686`

**How was OSM installed?**: OSM CLI v0.11.1-rc.1

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:
