### ISSUE TITLE
Handle tcp-server-first ports within the mesh

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#4313]
**Bug description**:

#3329 adds handling for ports with an `appProtocol` of `tcp-server-first` only when such services are referred to in an Egress policy. When a server-first port exists in the mesh, the TLS and HTTP inspector filters are still configured on the outbound-listener of a client to a server-first service, and Envoy's default 15s `listener_filters_timeout` is hit.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: Clients involved in server-first protocols immediately receive data from a service in the mesh when the service's port is `tcp-server-first`.

**Steps to reproduce the bug (as precisely as possible)**:
- Install OSM with permissive mode enabled
- Install a simple client and server:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: server
      containers:
        - name: server
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              nc -lkp 4242 -e sh -c "while yes; do :; done"
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
    - name: server
      port: 4242
      appProtocol: tcp-server-first
  selector:
    app: server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: client
      containers:
        - name: client
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              nc server 4242
```
When client and server are outside the mesh, the client receives an endless stream of `y` printed in its logs. When both are inside the mesh, the client gets stuck in `CrashLoopBackOff` and no logs are shown.

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:
