### ISSUE TITLE
Update MeshConfig Validating Webhook Configuration to prevent missing SAN errors

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#4353]
Update MeshConfig Validating Webhook Configuration to prevent the following error:
```json
{"level":"error","component":"kube-ingress","error":"Ingress gateway certificate spec must specify at least 1 SAN","time":"2021-11-10T01:32:47Z","file":"gateway.go:149","message":"Error updating ingress gateway cert and secret"}
```
The validation and enforcement of having at least 1 SAN in MeshConfig should be **also** done in the validating webhook.

Example MeshConfig CRO:
```yaml
apiVersion: config.openservicemesh.io/v1alpha1
kind: MeshConfig
metadata:
  name: osm-mesh-config
  namespace: kube-system
spec:
  certificate:
    certKeyBitSize: 2048
    ingressGateway:
      secret:
        name: osm-ingress-mtls
        namespace: ingress-nginx
      #subjectAltNames:
      #- ingress-nginx.ingress-nginx.cluster.local
      validityDuration: 1h
    serviceCertValidityDuration: 24h
  featureFlags:
    enableAsyncProxyServiceMapping: false
    enableEgressPolicy: true
    enableEnvoyActiveHealthChecks: false
    enableIngressBackendPolicy: true
    enableMulticlusterMode: false
    enableRetryPolicy: false
    enableSnapshotCacheMode: false
    enableWASMStats: true
  observability:
    enableDebugServer: true
    osmLogLevel: error
    tracing:
      enable: false
  sidecar:
    configResyncInterval: 0s
    enablePrivilegedInitContainer: false
    envoyImage: mcr.microsoft.com/oss/envoyproxy/envoy:v1.19.1
    envoyWindowsImage: envoyproxy/envoy-windows@sha256:c904fda95891ebbccb9b1f24c1a9482c8d01cbca215dd081fc8c8db36db85f85
    initContainerImage: mcr.microsoft.com/oss/openservicemesh/init:v0.11.1
    logLevel: error
    resources: {}
  traffic:
    enableEgress: true
    enablePermissiveTrafficPolicyMode: true
    inboundExternalAuthorization:
      enable: false
      failureModeAllow: false
      statPrefix: inboundExtAuthz
      timeout: 1s
    inboundPortExclusionList: []
    outboundIPRangeExclusionList: []
    outboundPortExclusionList: []
    useHTTPSIngress: false
```
