### ISSUE TITLE
Ingress Demos - use different "frontend" and target port in the service configuration

### ISSUE THREAD

**Issue by MarekLani** [openservicemesh/osm#4356]
Sample in Ingress Demo documentation articles (https://release-v0-11.docs.openservicemesh.io/docs/demos/ingress_contour/ and https://release-v0-11.docs.openservicemesh.io/docs/demos/ingress_k8s_nginx/) use the same port (14001) across all the resources. In case different "frontend" and target ports are set for the Service resource, the documentation doesn't make it clear what should be the port value of Ingress Backed resource. I would like to suggest to change the Service and Ingress configuration to one stated below + I suggest adding few lines on the purpose of Ingress Backend resource (if my understanding is correct, it configures the envoy proxy to respond to the Ingress Controller on the specified port). 

**Service**:
```
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 14001
  selector:
    app: httpbin
```

**Ingress**:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  namespace: httpbin
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpbin
            port:
              number: 80
```

Thank you.
