### ISSUE TITLE
ingress: Delete/recreate ingress client cert on rotate vs update with a feature flag

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#4394]
This GitHub Issue is to introduce a new feature flag, which when enabled, will change the way the Ingress client cert is rotated.

This is needed as a workaround for the following NGINX Ingress Controller bug:  https://github.com/kubernetes/ingress-nginx/issues/5608

The goal to create a new flag in MeshConfig:
```yaml
spec:
  certificate:
    certKeyBitSize: 2048
    ingressGateway:
      secret:
        name: osm-nginx-client-cert
        namespace: ingress-nginx
        recreateOnRotate: true ############## NEW KEY ##############
      subjectAltNames:
      - ingress-nginx.ingress.cluster.local
      validityDuration: 11m
    serviceCertValidityDuration: 1m
```

When the key `spec.ingressGateway.secret.recreateOnRotate` is enabled - OSM Controller should not just Update but Delete and reCreate the k8s secret with the TLS certificate.

Currently the update of the cert on rotate is done here:
1. On `announcements.CertificateRotated` event this function updates the cert: https://github.com/openservicemesh/osm/blob/98aef6dd0e464ae19819210085e6f24f99c5efae/pkg/ingress/gateway.go#L188
2. OSM then issues a new cert: https://github.com/openservicemesh/osm/blob/98aef6dd0e464ae19819210085e6f24f99c5efae/pkg/ingress/gateway.go#L69
3. Then stores it in the k8s secret: https://github.com/openservicemesh/osm/blob/98aef6dd0e464ae19819210085e6f24f99c5efae/pkg/ingress/gateway.go#L75
4. This operation is an `Update` on the existing certificate: https://github.com/openservicemesh/osm/blob/98aef6dd0e464ae19819210085e6f24f99c5efae/pkg/ingress/gateway.go#L101

The goal of this task is to introduce a flag, which when enabled, will change the behavior of https://github.com/openservicemesh/osm/blob/98aef6dd0e464ae19819210085e6f24f99c5efae/pkg/ingress/gateway.go#L101
and will introduce a `DELETE` above this line: https://github.com/openservicemesh/osm/blob/98aef6dd0e464ae19819210085e6f24f99c5efae/pkg/ingress/gateway.go#L98-L99

So:
```go
        // NEW
        if meshConfig.Spec.Certificate.IngressGateway.Secret.RecreateOnRotate {
                c.kubeClient.CoreV1().Secrets(secret.Namespace).Delete(context.Background(), sec.Name, metav1.DeleteOptions{})
        }

       // EXISTING
	_, err := c.kubeClient.CoreV1().Secrets(secret.Namespace).Create(context.Background(), sec, metav1.CreateOptions{})
	if apierrors.IsAlreadyExists(err) {
		_, err = c.kubeClient.CoreV1().Secrets(secret.Namespace).Update(context.Background(), sec, metav1.UpdateOptions{})
	}
```

---

# Why is this needed?

While testing OSM with NGINX ingress controller we discovered a case in which NGINX stops refreshing the mTLS certificate issued and saved in a k8s cert by OSM Controller.

## How this works
OSM is told to generate a certificate for the mTLS ingress with:
```bash
kubectl patch MeshConfig \
  osm-mesh-config \
  --namespace $OSM_NAMESPACE \
  --patch '{"spec":{"certificate":{"ingressGateway":{"subjectAltNames":["ingress-nginx.ingress-nginx.cluster.local"], "validityDuration":"24h", "secret":{"name":"osm-ingress-mtls","namespace":"ingress-nginx"}}}}}' \
  --type=merge
```
This will cause OSM to create a secret in namespace `ingress-nginx` called `osm-ingress-mtls`.
Once NGINX is installed and `Ingress` is configured with:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore
  namespace: bookstore
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # proxy_ssl_name for a service is of the form <service-account>.<namespace>.cluster.local
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_name "bookstore.bookstore.cluster.local";
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "ingress-nginx/osm-ingress-mtls"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
```
NGINX will start reading the cert from `ingress-nginx/osm-ingress-mtls`

We notice however that NGINX does not _always_ refresh the cert it stores in cache, even though OSM updates the cert with a newly rotated one. This causes "certificate expired" errors on the NGINX Ingress Controller pod and 503 errors on the clients connecting to NGINX.

A consistent way to fix this has been:
```bash
FN=osm-nginx-client-cert.temp.crt
kubectl get secrets -n ingress-nginx osm-nginx-client-cert -o yaml > $FN
kubectl delete secrets -n ingress-nginx osm-nginx-client-cert
kubectl apply -f $FN
```
