### ISSUE TITLE
Deployment PriorityClass in GKE is not working 

### ISSUE THREAD

**Issue by shawqi-voice** [openservicemesh/osm#4408]
**Bug description**:

**Affected area (please mark with X where applicable)**:

- Install                    [X]

**Expected behavior**:
successful installation 

**Steps to reproduce the bug (as precisely as possible)**:
affected components:

- [osm-bootstrap-deployment](https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/osm-bootstrap-deployment.yaml#L27)
- [osm-deployment](https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/osm-deployment.yaml#L30)
- [osm-injector-deployment](https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/osm-injector-deployment.yaml#L29)

installing the helm chart with the default value 

error message:
`Error creating: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]`

GKE by default limits the consumption of this priority class using `ResourceQuota`.
`kubectl get -n kube-system ResourceQuota gcp-critical-pods -o yaml`

```
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: gcp-critical-pods
  namespace: kube-system
spec:
  hard:
    pods: 1G
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
      - system-cluster-critical
```

**How was OSM installed?**:
Helm
**Anything else we need to know?**:

creating `ResourceQuota` in the same namespace osm is installed (ex. osm-system) should resolve the issue

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): 0.11.1
- Kubernetes version (use `kubectl version`): 1.20
- Size of cluster (number of worker nodes in the cluster): 2
- Others:

**Comment by trstringer** [comment]
I think the only way you can get in this situation is if the cluster has a configured `AdmissionConfiguration` specifying a `ResourceQuotaConfiguration` limiting pods with the `PriorityClass` in those two builtin priority classes.

Can you confirm the cluster does in fact have that?

**Comment by shawqi-voice** [comment]
> I think the only way you can get in this situation is if the cluster has a configured `AdmissionConfiguration` specifying a `ResourceQuotaConfiguration` limiting pods with the `PriorityClass` in those two builtin priority classes.
> 
> Can you confirm the cluster does in fact have that?

not sure if I can check any `AdmissionConfiguration` is implemented on GKE since I don't have access to the control plane, most likely there is, they are limiting it to the `kube-system` namespace only, my workaround was creating the same `ResourceQuota` in the same namespace where osm is deployed.

**Comment by trstringer** [comment]
Yeah that would make sense to resolve it. You shouldn't have had to specify `spec.hard` in the ResourceQuota though. Could you verify without that part of the ResourceQuota?

And for the sake of documenting this behavior, [here is an explanation of this (Kubernetes documentation)](https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default).

In my opinion, this is an implementation detail of a specific Kubernetes distro. I think the best approach here is through documentation.

**Comment by shawqi-voice** [comment]
> Yeah that would make sense to resolve it. You shouldn't have had to specify `spec.hard` in the ResourceQuota though. Could you verify without that part of the ResourceQuota?
> 
> And for the sake of documenting this behavior, [here is an explanation of this (Kubernetes documentation)](https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default).
> 
> In my opinion, this is an implementation detail of a specific Kubernetes distro. I think the best approach here is through documentation.

yes, just tested that, `spec.hard` is not needed.

**Comment by shawqi-voice** [comment]
agree on documenting this is enough, closing this.

**Comment by SoerenHenning** [comment]
I ran into the same issue. Is there any documentation on the OSM on how to fix it?

**Comment by alexanderxc** [comment]
@SoerenHenning, the solution is highlighted herein. In short, just deploy a yaml similar to the following after you create the namespace and before you deploy rook: 

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  # annotations:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: rook-critical-pods
  namespace: rook-ceph
spec:
  hard:
    pods: 1G
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
      - system-cluster-critical

```
You might add this to the common.yaml if you are not using helm. 

Best,
A
