### ISSUE TITLE
tcpSocket Kubernetes probes can't fail

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#4434]
**Bug description**: When specifying an unopened port for a `tcpSocket` probe, the probe passes when it should fail.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: A `tcpSocket` probe that fails when the Pod is outside the mesh should also fail when the Pod is inside the mesh.

**Steps to reproduce the bug (as precisely as possible)**:
First, add the following probe to docs/example/manifests/samples/httpbin/httpbin.yaml:
```
readinessProbe:
  tcpSocket:
    port: 14002 # not the port the server is running on
```

Then,
```
osm install
osm namespace add default
kubectl apply -f docs/example/manifests/samples/httpbin
```

At this point the pod becomes ready when it shouldn't. To verify that the same probe fails as expected outside the mesh:
```
osm namespace remove default
kubectl rollout restart deployment httpbin
kubectl describe po <new pod> # should show an event that the readiness probe is failing
```

**How was OSM installed?**: `osm install`

**Anything else we need to know?**:

I dug around to see if I could figure out why this is happening. The first thing I noticed is that the sidecar injector modifies the port for `tcpSocket` probes like it does for HTTP probes and programs the following listener:
```json
{
  "listener": {
    "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
    "name": "readiness_listener",
    "address": {
      "socket_address": {
        "address": "0.0.0.0",
        "port_value": 15902
      }
    },
    "filter_chains": [
      {
        "filters": [
          {
            "name": "envoy.filters.network.tcp_proxy",
            "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
              "stat_prefix": "health_probes",
              "cluster": "readiness_cluster",
              "access_log": [...]
            }
          }
        ]
      }
    ]
  }
}
```

And the cluster it references looks like:
```json
{
  "cluster": {
    "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
    "name": "readiness_cluster",
    "type": "STATIC",
    "load_assignment": {
      "cluster_name": "readiness_cluster",
      "endpoints": [
        {
          "lb_endpoints": [
            {
              "endpoint": {
                "address": {
                  "socket_address": {
                    "address": "127.0.0.1",
                    "port_value": 14002
                  }
                }
              }
            }
          ]
        }
      ]
    }
  }
}
```

Could this listener be causing all probes to port 15902 to succeed whether or not the port it proxies (14002) is actually open?

I tried modifying the injector to keep the same port (and skip adding the cluster and listener above), but I see the same behavior:
```diff
diff --git a/pkg/injector/health_probes.go b/pkg/injector/health_probes.go
index 04af3a6d..8c4df074 100644
--- a/pkg/injector/health_probes.go
+++ b/pkg/injector/health_probes.go
@@ -79,8 +79,6 @@ func rewriteProbe(probe *corev1.Probe, probeType, path string, port int32, conta
 			probe.HTTPGet.Path = path
 			newPath = probe.HTTPGet.Path
 		}
-	} else if probe.TCPSocket != nil {
-		definedPort = &probe.TCPSocket.Port
 	} else {
 		return nil
 	}
```

For reference, here's how the kubelet does `tcpSocket` probes: https://github.com/kubernetes/kubernetes/blob/v1.22.1/pkg/probe/tcp/tcp.go#L50

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
```
CLI Version: version.Info{Version:"v1.0.0-rc.3", GitCommit:"edb1d4531f350909d3eca77edee61a9f02056bd8", BuildDate:"2022-01-10-19:16"}
Mesh [osm] Version: version.Info{Version:"v1.0.0-rc.3", GitCommit:"abc559bb2282319bb2005231e3d5556560a50fa2", BuildDate:"2022-01-10-17:46"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"a5e4de7e277a707bd28d448bd75de58b4f1cdc22", GitTreeState:"clean", BuildDate:"2021-11-16T01:09:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (number of worker nodes in the cluster): 6
- Others:

**Comment by jaellio** [comment]
Steps followed: 
- installed osm
- added default namespace to the mesh
- added a tcpSocket probe to docs/example/manifests/samples/httpbin/httpbin.yaml
- applied docs/example/manifests/samples/httpbin/httpbin.yaml in the default namespace 

Verified the readiness probe fails, but the Pod is ready. A failed readiness probe should cause the Pod's ready state to change.

```yaml
Name:         httpbin-769db97645-tn428
Namespace:    default
Priority:     0
Node:         osm-worker/172.18.0.3
Start Time:   Wed, 02 Feb 2022 18:02:20 -0800
Labels:       app=httpbin
              osm-proxy-uuid=dbd41cc3-56c6-42f1-88b1-1682bebe8b99
              pod-template-hash=769db97645
Annotations:  kubectl.kubernetes.io/restartedAt: 2022-02-02T16:16:37-08:00
Status:       Running
IP:           10.244.1.33
IPs:
  IP:           10.244.1.33
Controlled By:  ReplicaSet/httpbin-769db97645
Init Containers:
  osm-init:
    ...
Containers:
  httpbin:
    Container ID:  containerd://0c7fcf9bb0b3d897233ef723d397ff14b6d169737d2b89068269160257404bfa
    Image:         kennethreitz/httpbin
    Image ID:      docker.io/kennethreitz/httpbin@sha256:599fe5e5073102dbb0ee3dbb65f049dab44fa9fc251f6835c9990f8fb196a72b
    Port:          14001/TCP
    Host Port:     0/TCP
    Command:
      gunicorn
      -b
      0.0.0.0:14001
      httpbin:app
      -k
      gevent
    State:          Running
      Started:      Wed, 02 Feb 2022 18:02:22 -0800
    Ready:          True
    Restart Count:  0
    Readiness:      tcp-socket :15902 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4wj87 (ro)
  envoy:
    Container ID:  containerd://050a4881326cd444e6640a6f046cea5b6b3aabc86be605b3e24ce5e9b2962d23
    Image:         envoyproxy/envoy-alpine@sha256:6502a637c6c5fba4d03d0672d878d12da4bcc7a0d0fb3f1d506982dde0039abd
    Image ID:      docker.io/envoyproxy/envoy-alpine@sha256:6502a637c6c5fba4d03d0672d878d12da4bcc7a0d0fb3f1d506982dde0039abd
    Ports:         15000/TCP, 15003/TCP, 15010/TCP, 15902/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      envoy
    Args:
      --log-level
      debug
      --config-path
      /etc/envoy/bootstrap.yaml
      --service-cluster
      httpbin.
      --bootstrap-version 3
    State:          Running
      Started:      Wed, 02 Feb 2022 18:02:22 -0800
    Ready:          True
    Restart Count:  0
    Environment:
      POD_UID:           (v1:metadata.uid)
      POD_NAME:         httpbin-769db97645-tn428 (v1:metadata.name)
      POD_NAMESPACE:    default (v1:metadata.namespace)
      POD_IP:            (v1:status.podIP)
      SERVICE_ACCOUNT:   (v1:spec.serviceAccountName)
    Mounts:
      /etc/envoy from envoy-bootstrap-config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4wj87 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-api-access-4wj87:
    ...
  envoy-bootstrap-config-volume:
    ...
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/arch=amd64
                 kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age    From               Message
  ----     ------     ----   ----               -------
  Normal   Scheduled  7m16s  default-scheduler  Successfully assigned default/httpbin-769db97645-tn428 to osm-worker
  Normal   Pulled     7m16s  kubelet            Container image "localhost:5000/init:38495544cd0bb2df16a9c88a8a4bf638b7ef093b" already present on machine
  Normal   Created    7m16s  kubelet            Created container osm-init
  Normal   Started    7m16s  kubelet            Started container osm-init
  Normal   Pulled     7m15s  kubelet            Container image "kennethreitz/httpbin" already present on machine
  Normal   Created    7m15s  kubelet            Created container httpbin
  Normal   Started    7m15s  kubelet            Started container httpbin
  Normal   Pulled     7m15s  kubelet            Container image "envoyproxy/envoy-alpine@sha256:6502a637c6c5fba4d03d0672d878d12da4bcc7a0d0fb3f1d506982dde0039abd" already present on machine
  Normal   Created    7m15s  kubelet            Created container envoy
  Normal   Started    7m15s  kubelet            Started container envoy
  Warning  Unhealthy  7m14s  kubelet            Readiness probe failed: dial tcp 10.244.1.33:15902: connect: connection refused
```
