### ISSUE TITLE
Remove "expiration" field from `osm-ca-bundle` secret

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm#4467]
**Please describe the Improvement and/or Feature Request**

When Tresor is selected as OSM's certificate provider the `osm-ca-bundle` secret has the following form:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
      name: osm-ca-bundle
      namespace: osm-system
data:
  ca.crt: <base64 encoded root cert>
  expiration: <base64 encoded ISO 8601 certificate expiration date; for example: 2031-01-11T23:15:09.299Z>
  private.key: <base64 encoded private key>
```

If the user wishes to bring their own root certificate rather than have it be created by OSM they must create an `osm-ca-bundle` secret of the same form prior to installing OSM.

The expiration field in the secret's data is the expiration date of the encoded root cert in `ca.crt`. When a user brings their own root cert there is no verification that the expiration field value is equivalent to the encoded root cert. Additionally, the expiration field is redundant since the expiration can be obtained from the `ca.crt`.

I propose that we remove the expiration field from the `osm-ca-bundle` secret when the secret is created by OSM and no longer make it a required field when users bring their own cert and create the `osm-ca-bundle` secret for themselves.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [x]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]
