### ISSUE TITLE
Helm Chart does not support HTTPS Ingress for ingress-nginx

### ISSUE THREAD

**Issue by mgugger** [openservicemesh/osm#4511]
**Please describe the Improvement and/or Feature Request**
When installing the helm chart, there is no way in values to set the ingress-nginx https config as in this tutorial:
https://release-v1-0.docs.openservicemesh.io/docs/demos/ingress_k8s_nginx/

Specifically, the following configuration block cannot be set through Helm as the chart only allows for contour to be set:
```
certificate:
  ingressGateway:
    secret:
      name: osm-nginx-client-cert
      namespace: <osm-namespace> # replace <osm-namespace> with the namespace where OSM is installed
    subjectAltNames:
    - ingress-nginx.ingress-nginx.cluster.local
    validityDuration: 24h
```

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [X]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
Since ingress-nginx is specifically mentioned in the osm docs as a possibility, I'd be great that the Helm Chart allows for settings the required ingressGateway certificate config. Otherwise the chart cannot be leveraged for ingress-nginx. The relevant part in the helm chart templates is here:
https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/preset-mesh-config.yaml#L35-L48
