### ISSUE TITLE
Question: is there any way to monitor tcp based (Postgres) traffic?

### ISSUE THREAD

**Issue by benediktwetzel** [openservicemesh/osm#4735]
I use PostgresQL as database. The network protocol is TCP (set by port name). 

I want to monitor the network traffic between my components and Postgres. But I am not able to collect any metrics from or to Postgres (only metrics with label value "unknown" are available). In the documentation I found the following: "HTTP requests that invoke a local response from Envoy have “unknown” destination_* labels on metrics. ". - But is there any way to configure my clients, Osm, Envoy or Postgres to enable monitoring?

I have set the envoy log level to debug, but I can't find any reason for a "local response" from the envoy proxy.

I would be very happy if someone has an idea!

**Comment by nojnhuh** [comment]
@shashankram Yes, the `osm_request_total` and `osm_request_duration` metrics are only expected to work for HTTP traffic currently. Envoy exposes TCP metrics on [clusters](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats) and [listeners](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats) which may be enough depending on what you need, but you may need to tweak the default Prometheus configuration for them to be scraped:
https://github.com/openservicemesh/osm/blob/5a885ef60653fb4c987c847b33ece14bad56dfba/charts/osm/templates/prometheus-configmap.yaml#L57-L59

Envoy provides a [Postgres filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/postgres_proxy_filter) which exposes metrics specific to Postgres traffic, but currently there's no way for OSM to configure that.

**Comment by shashankram** [comment]
Since PostgreSQL will use TCP-based (appProtocol: tcp) routing in OSM, at the very least default metrics for TCP clusters should be published by Envoy. 

We can provide further metrics by:
1. Adding custom metrics/labels using WASM for TCP: #2506 
2. Allow setting `appProtocol: postgresql` on service ports, where we add the additional `postgres_proxy` filter for such ports

@benediktwetzel, are you able to retrieve the default [metrics for TCP based clusters](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#tcp-statistics)?

**Comment by benediktwetzel** [comment]
May i can reopen this issue. 

I am not able to retrieve the envoy metrics for TCP based clusters.

I have added your snippet to my service monitor: 

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-pod-monitor-tcp
spec:
  podMetricsEndpoints:
  - interval: 10s
    metricRelabelings:
    - action: keep 
      regex: '(envoy_server_live|envoy_cluster_health_check_.*|envoy_cluster_upstream_rq_xx|envoy_cluster_upstream_cx_active|envoy_cluster_upstream_cx_tx_bytes_total|envoy_cluster_upstream_cx_rx_bytes_total|envoy_cluster_upstream_rq_total|envoy_cluster_upstream_cx_destroy_remote_with_active_rq|envoy_cluster_upstream_cx_connect_timeout|envoy_cluster_upstream_cx_destroy_local_with_active_rq|envoy_cluster_upstream_rq_pending_failure_eject|envoy_cluster_upstream_rq_pending_overflow|envoy_cluster_upstream_rq_timeout|envoy_cluster_upstream_rq_rx_reset|envoy_cluster_upstream_rq_retry.*|^osm.*)' 
      sourceLabels:
      - __name__
    - action: keep
      regex: envoy_.*osm_request_(total|duration_ms_(bucket|count|sum))
      sourceLabels:
      - __name__
    - action: replace
      regex: envoy_response_code_(\d{3})_source_namespace_.*_source_kind_.*_source_name_.*_source_pod_.*_destination_namespace_.*_destination_kind_.*_destination_name_.*_destination_pod_.*_osm_request_total
      sourceLabels:
      - __name__
      targetLabel: response_code
    - action: replace
      regex: envoy_response_code_\d{3}_source_namespace_(.*)_source_kind_.*_source_name_.*_source_pod_.*_destination_namespace_.*_destination_kind_.*_destination_name_.*_destination_pod_.*_osm_request_total
      sourceLabels:
      - __name__
      targetLabel: source_namespace
    - action: replace
      regex: envoy_response_code_\d{3}_source_namespace_.*_source_kind_(.*)_source_name_.*_source_pod_.*_destination_namespace_.*_destination_kind_.*_destination_name_.*_destination_pod_.*_osm_request_total
      sourceLabels:
      - __name__
      targetLabel: source_kind
    - action: replace
      regex: envoy_response_code_\d{3}_source_namespace_.*_source_kind_.*_source_name_(.*)_source_pod_.*_destination_namespace_.*_destination_kind_.*_destination_name_.*_destination_pod_.*_osm_request_total
      sourceLabels:
      - __name__
      targetLabel: source_name
    - action: replace
      regex: envoy_response_code_\d{3}_source_namespace_.*_source_kind_.*_source_name_.*_source_pod_(.*)_destination_namespace_.*_destination_kind_.*_destination_name_.*_destination_pod_.*_osm_request_total
      sourceLabels:
      - __name__
      targetLabel: source_pod
    - action: replace
      regex: envoy_response_code_\d{3}_source_namespace_.*_source_kind_.*_source_name_.*_source_pod_.*_destination_namespace_(.*)_destination_kind_.*_destination_name_.*_destination_pod_.*_osm_request_total
      sourceLabels:
      - __name__
      targetLabel: destination_namespace
    - action: replace
      regex: envoy_response_code_\d{3}_source_namespace_.*_source_kind_.*_source_name_.*_source_pod_.*_destination_namespace_.*_destination_kind_(.*)_destination_name_.*_destination_pod_.*_osm_request_total
      sourceLabels:
      - __name__
      targetLabel: destination_kind
    - action: replace
      regex: envoy_response_code_\d{3}_source_namespace_.*_source_kind_.*_source_name_.*_source_pod_.*_destination_namespace_.*_destination_kind_.*_destination_name_(.*)_destination_pod_.*_osm_request_total
      sourceLabels:
      - __name__
      targetLabel: destination_name
    - action: replace
      regex: envoy_response_code_\d{3}_source_namespace_.*_source_kind_.*_source_name_.*_source_pod_.*_destination_namespace_.*_destination_kind_.*_destination_name_.*_destination_pod_(.*)_osm_request_total
      sourceLabels:
      - __name__
      targetLabel: destination_pod
    - action: replace
      regex: .*(osm_request_total)
      sourceLabels:
      - __name__
      targetLabel: __name__
    - action: replace
      regex: envoy_source_namespace_(.*)_source_kind_.*_source_name_.*_source_pod_.*_destination_namespace_.*_destination_kind_.*_destination_name_.*_destination_pod_.*_osm_request_duration_ms_(bucket|sum|count)
      sourceLabels:
      - __name__
      targetLabel: source_namespace
    - action: replace
      regex: envoy_source_namespace_.*_source_kind_(.*)_source_name_.*_source_pod_.*_destination_namespace_.*_destination_kind_.*_destination_name_.*_destination_pod_.*_osm_request_duration_ms_(bucket|sum|count)
      sourceLabels:
      - __name__
      targetLabel: source_kind
    - action: replace
      regex: envoy_source_namespace_.*_source_kind_.*_source_name_(.*)_source_pod_.*_destination_namespace_.*_destination_kind_.*_destination_name_.*_destination_pod_.*_osm_request_duration_ms_(bucket|sum|count)
      sourceLabels:
      - __name__
      targetLabel: source_name
    - action: replace
      regex: envoy_source_namespace_.*_source_kind_.*_source_name_.*_source_pod_(.*)_destination_namespace_.*_destination_kind_.*_destination_name_.*_destination_pod_.*_osm_request_duration_ms_(bucket|sum|count)
      sourceLabels:
      - __name__
      targetLabel: source_pod
    - action: replace
      regex: envoy_source_namespace_.*_source_kind_.*_source_name_.*_source_pod_.*_destination_namespace_(.*)_destination_kind_.*_destination_name_.*_destination_pod_.*_osm_request_duration_ms_(bucket|sum|count)
      sourceLabels:
      - __name__
      targetLabel: destination_namespace
    - action: replace
      regex: envoy_source_namespace_.*_source_kind_.*_source_name_.*_source_pod_.*_destination_namespace_.*_destination_kind_(.*)_destination_name_.*_destination_pod_.*_osm_request_duration_ms_(bucket|sum|count)
      sourceLabels:
      - __name__
      targetLabel: destination_kind
    - action: replace
      regex: envoy_source_namespace_.*_source_kind_.*_source_name_.*_source_pod_.*_destination_namespace_.*_destination_kind_.*_destination_name_(.*)_destination_pod_.*_osm_request_duration_ms_(bucket|sum|count)
      sourceLabels:
      - __name__
      targetLabel: destination_name
    - action: replace
      regex: envoy_source_namespace_.*_source_kind_.*_source_name_.*_source_pod_.*_destination_namespace_.*_destination_kind_.*_destination_name_.*_destination_pod_(.*)_osm_request_duration_ms_(bucket|sum|count)
      sourceLabels:
      - __name__
      targetLabel: destination_pod
    - action: replace
      regex: .*(osm_request_duration_ms_(bucket|sum|count))
      sourceLabels:
      - __name__
      targetLabel: __name__
    path: /stats/prometheus
    targetPort: 15010
  selector:
    matchLabels:
      monitoring: enabled
```
Do you have an idea what could be the problem?
