### ISSUE TITLE
Question regarding collecting metrics directly from application pods in the mesh

### ISSUE THREAD

**Issue by teomanS** [openservicemesh/osm#4875]
There is a documentation for getting envoy sidecar metrics from BYO Prometheus. Documentation link is https://release-v0-11.docs.openservicemesh.io/docs/guides/observability/metrics/#byo-prometheus 
on the other hand there is no documentation about getting application metrics from pods which have envoy proxy sidecar.

Our application publish it's own metrics via localhost:8070/actuator/promethues url and Our deployment has these annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8070"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"

But openservicemesh is overwritting pod's annotations with these:
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15010"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"

I tried to add annotations to service definition:
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/scrape: "true"
  name: monitoring-svc
  namespace: dev-ns
spec:
  ports:
  - name: http-monitoring
    port: 80
    protocol: TCP
    targetPort: 8070
  selector:
    app: myapp
  sessionAffinity: None
  type: ClusterIP

but I could not achieved, I saw "Get "http://172.17.6.124:8070/actuator/prometheus": read tcp 172.17.6.82:50834->172.17.6.124:8070: read: connection reset by peer" error at prometheus ->  Targets page.

**Comment by steeling** [comment]
the sidecar will attempt to apply mTLS for that route. You will need to a) change your scraping to HTTPS, and b) setup an [IngressBackend](https://release-v1-1.docs.openservicemesh.io/docs/api_reference/policy/v1alpha1/#policy.openservicemesh.io/v1alpha1.IngressBackend) for that route such that it does not attempt to verify the clients certificate as part of mTLS.

Let's keep this issue open, as this should be a more seamless experience for users

**Comment by teomanS** [comment]
> @teomanS does the `http-monitoring` service accept traffic from other pods in the mesh on port 8070 or is this service only used for scraping metrics using a Prometheus client?
 `http-monitoring`  created for just exposing application metrics but It accepts connections from other pods. 

By the way I added monitoring namespace  ,which prometheus is installed , to servicemesh and auto injected sidecars to pods.
My error change to "http://172.17.6.124:8070/actuator/prometheus:EOF"  error.  I'm able to get metrics from pod at monitoring namespace with curl command via http-monitoring service url. 

Would you suggest adding the monitoring namespace to the service mesh?

**Comment by steeling** [comment]
@teomanS remember that you'll need to use HTTPS not HTTP

**Comment by teomanS** [comment]
> prometheus.io/scheme: https

I changed service definition:
apiVersion: v1
kind: Service
metadata:
annotations:
prometheus.io/path: /actuator/prometheus
prometheus.io/scrape: "true"
prometheus.io/scheme: https
name: monitoring-svc
namespace: dev-ns
spec:
ports:

name: http-monitoring
port: 80
protocol: TCP
targetPort: 8070
selector:
app: myapp
sessionAffinity: None
type: ClusterIP

and changed the ingressBackend definition:
kind: IngressBackend
metadata:
  name: monitoring-ingress-backend
  namespace: dev-ns
spec:
  backends:
  - name: monitoring-svc
    port:
      number: 8080
      protocol: https
  sources:
  - kind: Service
    name: nginx-ingress-nginx-ingress
    namespace: ingress-nginx-controller
status:
  currentStatus: committed
  reason: successfully committed by the system

Latest error is:
"Get "https://172.17.6.124:8070/actuator/prometheus": EOF "

**Comment by steeling** [comment]
@shashankram do we need not support referencing pods by IP directly? If so, this would then turn into a feature request to allow pods to be addressed by their IP, which I would expect would work as a user as well.

There's also likely other use cases where clients may want to leverage an IP address directly

**Comment by shashankram** [comment]
> @teomanS does the `http-monitoring` service accept traffic from other pods in the mesh on port 8070 or is this service only used for scraping metrics using a Prometheus client?

@teomanS, please answer this question so I can understand your scenario better.

> do we need not support referencing pods by IP directly?

@steeling could you clarify the scenario further?

**Comment by shashankram** [comment]
> sorry typo, do we support HTTP calls to an IP address directly with pods in a mesh? ie: curl http://x.x.x.x:8080/

Currently no, see https://github.com/openservicemesh/osm/issues/2097

**Comment by teomanS** [comment]
> does the `http-monitoring` service accept traffic from other pods in the mesh on port 8070 or is this service only used for scraping metrics using a Prometheus client?

we are using this service only for scraping metrics using a Prometheus client.

**Comment by teomanS** [comment]
Hi,

For workaround I changed the prometheus scraping configuration and replaced the __address__ tag with the full kubernetes service dns name.

I added these lines under kubernetes-service-endpoints job's configuration:
```
        - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_namespace]
          action: replace
          regex: (.*);(.*)
          replacement: $1.$2.svc
          target_label: __address__    
```

After this change, prometheus started to access endpoints via kubernetes svc url rather than IP:Port combination.
Targets are listed like this:
"http://monitoring-svc.dev-ns/actuator/prometheus/ " and target status is "UP" , so I'm able to get application metrics with this configuration.

Default 'kubernetes-service-endpoints' configuration is:
```
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name
```

Modified and succesfully working with OSM version is:
```
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name
        - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_namespace]
          action: replace
          regex: (.*);(.*)
          replacement: $1.$2.svc
          target_label: __address__          
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__   
```
