### ISSUE TITLE
Update Traffic Split SMI Spec to v1alpha4 to support A/B Testing

### ISSUE THREAD

**Issue by fsforza** [openservicemesh/osm#4880]
**Please describe the Improvement and/or Feature Request**
It would be very nice that Open Service Mesh updates Traffic Split to version v1alpha4 to offer the A/B testing feature
https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-split/v1alpha4/traffic-split.md

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [x]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
My use case is similar to the one used as A/B testing example in the TrafficSplit v1alpha4 doc:

```yaml
kind: TrafficSplit
metadata:
  name: ab-test
spec:
  service: website
  matches:
  - kind: HTTPRouteGroup
    name: ab-test
  backends:
  - service: website-v1
    weight: 0
  - service: website-v2
    weight: 100
---
kind: HTTPRouteGroup
metadata:
  name: ab-test
matches:
- name: firefox-users
  headers:
    user-agent: ".*Firefox.*"
```

I need to route a client call to a specific backend version depending to an http header put into the request.
In this example all the Firefox users, according to the user-agent header, will be routed to the website-v2 Kubernetes service.

Thanks!
