### ISSUE TITLE
Specifying root service port to a port other than containerPort/TargetPort of the leaf service doesn't not work

### ISSUE THREAD

**Issue by jkotalik** [openservicemesh/osm#4894]
According to the SMI documentation, we can have a configuration where the root service port is 8080 and the leaf service has a targetPort other than 8080: https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-split/v1alpha4/traffic-split.md#ports
```yaml
kind: Service
apiVersion: v1
metadata:
  name: birds
spec:
  selector:
    app: birds
  ports:
  - name: grpc
    port: 8080
  - name: rest
    port: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: blue-birds
spec:
  selector:
    app: birds
    color: blue
  ports:
  - name: grpc
    port: 8080
  - name: rest
    port: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: green-birds
spec:
  selector:
    app: birds
    color: green
  ports:
  - name: grpc
    port: 8080
    targetPort: 8081 <--- 8081 would match the container port of 
  - name: rest
    port: 9090
```

When trying this on the `httpbin` canary rollout sample though, I wasn't able to see this sample work with this kind of configuration. https://release-v1-0.docs.openservicemesh.io/docs/demos/canary_rollout/

## Repro steps

Follow the tutorial in https://release-v1-0.docs.openservicemesh.io/docs/demos/canary_rollout/, except we are going to update the yaml definitions of the services and apply those instead

httpbin.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  namespace: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: httpbin
```

httpbin-v1.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: httpbin-v1
  namespace: httpbin
  labels:
    app: httpbin
    version: v1
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 14001
  selector:
    app: httpbin
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-v1
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - image: simonkowallik/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        command: ["gunicorn", "-b", "0.0.0.0:14001", "httpbin:app", "-k", "gevent"]
        ports:
        - containerPort: 14001
        env:
        - name: XHTTPBIN_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```

Where we deploy these yamls in step 3 and 4 instead of the ones in the raw github link.

On Step 6, instead of getting a 200, we are consistently seeing 503s.

## Other details

It seems like there are some oddities in this behavior where if we change the targetPort on the root service to 14001, then change it back to 8080, the configuration is still working.
