### ISSUE TITLE
rbac_access_denied_matched_policy[none] by using AuthenticatedPrincipal

### ISSUE THREAD

**Issue by thorker** [openservicemesh/osm#5042]
**Bug description**:
Currently, we are testing AKS 1.24 & OSM 1.2.0 and as soon as we added the AuthenticatedPrincipal to our IngressBackend, the connectivity breaks. In the envoy logs we see the responsecodedetails rbac_access_denied_matched_policy[none].

We are using the configuration from the [guide](https://release-v1-2.docs.openservicemesh.io/docs/demos/ingress_k8s_nginx/) at another setup with AKS 1.23.8 and OSM 1.1.1 and it's working fine.

Do we missed some configurations to work with version 1.2.0?

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ x ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**How was OSM installed?**:
AKS-AddOn

**Environment**:
- OSM version (use `osm version`): 1.2.0
- Kubernetes version (use `kubectl version`): 1.24.3

**Comment by shashankram** [comment]
@thorker could you share the following configurations (please redact sensitive/PII data):
1. Backend k8s service yaml
2. IngressBackend service yaml
3. MeshConfig yaml: kubectl get meshconfig osm-mesh-config -n <osm-namespace> -o yaml

Additionally, could you confirm if [HTTP ingress](https://release-v1-2.docs.openservicemesh.io/docs/demos/ingress_k8s_nginx/#http-ingress) and `HTTPS ingress with one-way TLS (skipClientCertValidation: true)` works?

**Comment by thorker** [comment]
HTTP Ingress & HTTPS ingress (skipClientCertValidation: true) works. 

Configurations are the same in both AKS, but in the new version it doesn't work anymore. We only adapted the guide to your services.

```
spec:
  certificate:
    certKeyBitSize: 2048
    ingressGateway:
      secret:
        name: osm-nginx-client-cert
        namespace: kube-system
      subjectAltNames:
        - ingress-nginx.ingress-nginx.cluster.local
      validityDuration: 24h
    serviceCertValidityDuration: 24h
  featureFlags:
    enableAsyncProxyServiceMapping: false
    enableEgressPolicy: true
    enableEnvoyActiveHealthChecks: false
    enableIngressBackendPolicy: true
    enableRetryPolicy: false
    enableSnapshotCacheMode: false
    enableWASMStats: true
  observability:
    enableDebugServer: true
    osmLogLevel: error
    tracing:
      enable: false
  sidecar:
    configResyncInterval: 0s
    enablePrivilegedInitContainer: false
    localProxyMode: Localhost
    logLevel: error
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 1Gi
    tlsMaxProtocolVersion: TLSv1_3
    tlsMinProtocolVersion: TLSv1_2
  traffic:
    enableEgress: true
    enablePermissiveTrafficPolicyMode: true
    inboundExternalAuthorization:
      enable: false
      failureModeAllow: false
      statPrefix: inboundExtAuthz
      timeout: 1s
```

```
spec:
  backends:
    - name: acc000-def-example
      port:
        number: 8080
        protocol: https
      tls:
        skipClientCertValidation: false
  sources:
    - kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
    - kind: AuthenticatedPrincipal
      name: ingress-nginx.ingress-nginx.cluster.local
```

```
apiVersion: v1
kind: Service
metadata:
  name: acc000-def-example
  namespace: acc000-example-box-def
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
```
