### ISSUE TITLE
create the meshedcluster object

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#5168]
Should look something like

```
apiVersion: v1alpha1
kind: MeshedCluster
metadata:
 name: us-east1
spec:
 caBundle: ... # bytes
 // We again note that the network object may not be necessary, depending on the MCS implementation, and if it supports populating
 // the endpoint slices through a proxy already. That is to say, whether the network is flat or not may be transparent
 // to us.
 Network:
   type: Tunneled # value of `Tunneled`, `Flat`.
   tunnel: # object
     address: # IP address. one of address or serviceImport must be defined
     serviceImport:
       name: <name>
       namespace: <namespace>
```

Create both the CRD, go structs, generated client code, and add to the informer cache
