### ISSUE TITLE
Update "Ingress with Kubernetes Nginx Ingress Controller" demo documentation to clarify namespace for proxy-ssl-secret setting

### ISSUE THREAD

**Issue by marlowp** [openservicemesh/osm#5275]
On the "Ingress with Kubernetes Nginx Ingress Controller" demo article it specifies the following annotations for the NGINX config when enabling HTTPS:

```yaml
annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # proxy_ssl_name for a service is of the form <service-account>.<namespace>.cluster.local
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_name "httpbin.httpbin.cluster.local";
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "osm-system/osm-nginx-client-cert"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
```

To be consistent with the rest of the documentation on this page is should also clarify that the namespace for the `proxy-ssl-secret` is the namespace OSM was installed in, which might not necessarily be `osm-system`. For example it is `kube-system` by default in AKS.

So something like:

```yaml
annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # proxy_ssl_name for a service is of the form <service-account>.<namespace>.cluster.local
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_name "httpbin.httpbin.cluster.local";
    # replace <osm-namespace> with the namespace where OSM is installed
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "<osm-namespace>/osm-nginx-client-cert" 
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
```
