### ISSUE TITLE
Add resource limits to the OSM controller pod in CI

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#894]
Add resource limits to the OSM controller pod in CI

```
limits:
  cpu: 700m
  memory: 100Mi
requests:
  cpu: 100m
  memory: 20Mi
```

The goal of this is to get CI to crash loudly when we cross (for some reason) these boundaries.
This would be good to do on our local dev environments as well.
